### PR TITLE
Sort recipients index in descending order by date created

### LINKED ISSUE #56: Sort recipients by most recent instead of least recent

### PR DESCRIPTION
**Pull request by qubist**
Used https://stackoverflow.com/questions/12764765/ to learn how sorting 
like this works.

I didn't add a test for this because there wasn't a recipients_controller test there already and I didn't know how to add one.

Closes #56

### CODE REVIEW

**Comment by qubist** [comment]
Happy to add tests with help if you think it's needed @lbraun

**Comment by qubist** [comment]
Oh I found where the tests for this are: in `recipients_spec.rb` in the _features_ folder. Looks like it doesn't test order.

**Comment by qubist** [comment]
Added a test for order :)) figured it out on my own :))

**Comment by lbraun** [comment]
Nice!!! Yeah, feature tests (a.k.a. system tests, integration tests) test everything in a sense because they actually render the page and test what's displayed, so all the pieces (model, view, and controller) have to be working for them to pass.

The downside is that they are slow and not very exact. But I tend to write a lot more feature tests than controller tests.

**Comment by lbraun** [comment]
Excellent @qubist , thank you!!

**Pull request merged**
